### ISSUE TITLE
In SampleApp, file set_07, the function that displays only the outline of a circle does not work as expected

### ISSUE THREAD

**Issue by jiaoshouwu** [BRTSG-FOSS/EveApps#14]
http://www.brtcommunity.com/index.php?topic=329.0

`ConcetricCirciles` function presume that the background is supposed to be black.

Some tests:

![image](https://user-images.githubusercontent.com/778592/132275787-b15f8cce-95bd-41b0-9952-d314c96625e4.png)

![image](https://user-images.githubusercontent.com/778592/132275819-353ffb98-5c6f-4b5b-959b-dcbeedc1ec47.png)

![image](https://user-images.githubusercontent.com/778592/132275840-5def371b-081f-493c-b336-dd23ad5aa064.png)

**Comment by brtchip-tuannguyen** [comment]
For changing background purpose, I see that using Stencil is more easier.
Updated SampleApp to use STENCIL, so user can use any background color.

Screenshot:

![image](https://user-images.githubusercontent.com/48436368/140515827-2b61f60b-d50a-45d8-8e01-ec6ce1f455ee.png)


![image](https://user-images.githubusercontent.com/48436368/140515952-165fafd4-8b42-46c1-a72d-27d6515bf1ec.png)
