### ISSUE TITLE
DemoUnicode: Incorrect Japanese word translations

### ISSUE THREAD

**Issue by okuoku** [BRTSG-FOSS/EveApps#18]
On DemoUnicode application, some Japanese words are incorrectly translated from English ones.

![image](https://user-images.githubusercontent.com/100813/150823124-df92b89d-4cfe-4c92-8c33-b184f5099e71.png)

"[日本人](https://en.wikipedia.org/wiki/Japanese_people)" here should be "[日本語](https://en.wikipedia.org/wiki/Japanese_language)" https://github.com/BRTSG-FOSS/EveApps/blob/f607dfdb09fbe0aa0400ef5c448242589dac3864/DemoApps/Unicode/Test/font/Demo_texts_ja.txt#L1

![image](https://user-images.githubusercontent.com/100813/150823167-b702636c-199d-4b2e-b765-4e9dcf7d015f.png)

"に" here should be "オン" instead. https://github.com/BRTSG-FOSS/EveApps/blob/f607dfdb09fbe0aa0400ef5c448242589dac3864/DemoApps/Unicode/Test/font/Demo_texts_ja.txt#L3

**Comment by brtchip-tuannguyen** [comment]
Fixed in commit 00de5dd

![image](https://user-images.githubusercontent.com/48436368/150901358-aecb789c-d2c6-4e6f-a3b8-be2bccb4de3c.png)

**Comment by okuoku** [comment]
Thanks for the quick fix but it seems `txtStrJa` update has some leftovers for `日本語`(Japanese) part of text and keyboards. We need following in addition to https://github.com/BRTSG-FOSS/EveApps/commit/00de5ddcc947a0ba7606cf2f18efde29d071615e

```diff
diff --git a/DemoApps/Unicode/Src/DemoUnicode.c b/DemoApps/Unicode/Src/DemoUnicode.c
index 2fef68d..7baf296 100644
--- a/DemoApps/Unicode/Src/DemoUnicode.c
+++ b/DemoApps/Unicode/Src/DemoUnicode.c
@@ -82,15 +82,15 @@ const char8_t *txtStrEn[] = {
        NULL
 };
 const char8_t *txtStrJa[] = {
-       u8"\x0045\x0046\x0042",
-       u8"\x0039\x0035\x003a\x0039\x003e\x003f\x0036\x0040\x0038\x003b\x003c\x002b\x0043\x0044\x0028\x0047\x002a\x0041\x0033\x0048\x002d",
+       u8"\x0043\x0044\x0046",
+       u8"\x0038\x0034\x0039\x0038\x003d\x003e\x0035\x003f\x0037\x003a\x003b\x002a\x0041\x0042\x0027\x0045\x0029\x0040\x0032\x0047\x002c",
        u8"\x0036\x003f",
        u8"\x0036\x003c",
-       u8"\x0009\x000b\x000c\x000d\x000e\x000f\x0010\x0011\x0012\x0013",
-       u8"\x0023\x0026\x0019\x0020\x001a\x0034\x0028\x0029\x0031\x0021",
-       u8"\x0024\x0027\x001f\x002b\x001b\x001c\x002e\x002a\x0032",
-       u8"\x0025\x001e\x0022\x002c\x001d\x002f\x0030",
-       u8"\x0001\x0018\x0007\x0005\x0015\x0017\x0016\x0014\x0004\x0003\x0006\x0008\x0002\x0002",
+       u8"\x0008\x0009\x000b\x000c\x000d\x000e\x000f\x0010\x0011\x0012",
+       u8"\x0022\x0025\x0018\x001f\x0019\x0033\x0027\x0028\x0030\x0020",
+       u8"\x0023\x0026\x001e\x002a\x001a\x001b\x002d\x0029\x0031",
+       u8"\x0024\x001d\x0021\x002b\x001c\x002e\x002f",
+       u8"\x0001\x0017\x0006\x0004\x0014\x0016\x0015\x0013\x0003\x0002\x0005\x0007\x0001\x0001",
        NULL
 };
 const char8_t *txtStrHi[] = {
```

to see correct button for Japanese language selection and demonstrated on-screen keyboard.

![image](https://user-images.githubusercontent.com/100813/150919896-78cbbce0-c80d-4eb7-972e-59879d416283.png)

(Actually, [Japanese kana keyboard](https://en.wikipedia.org/wiki/Japanese_language_and_computers#/media/File:KB_Japanese.svg) has more [Hiragana](https://en.wikipedia.org/wiki/Hiragana) characters on it but I guess implementing fully-fledged on-screen Japanese keyboard is obviously out-of-scope of the demo.)

**Comment by brtchip-tuannguyen** [comment]
Thanks @okuoku, just committed your patch to commit b292da4.

[Japanese kana keyboard](https://en.wikipedia.org/wiki/Japanese_language_and_computers#/media/File:KB_Japanese.svg) is a nice example, we will use it to improve this demo in the future.
