### ISSUE TITLE
The #include guard macro for header file is missing

### ISSUE THREAD

**Issue by BRTSG-FOSS** [BRTSG-FOSS/EveApps#3]
![image](https://user-images.githubusercontent.com/83748190/131455740-a0faa078-30ed-4d35-a163-fd225330e8ad.png)

```C
#ifndef  FFCONF_H
#define FFCONF_H

......
#endif
```

**Comment by ftdi-paul-jiao** [comment]
checked R14B version, the original code has no such #include guard macro for ffconf.h , like below: 

![image](https://user-images.githubusercontent.com/13127756/131461352-dbe55302-5a33-4b5b-8b04-f4ff4d10fdac.png)
