### ISSUE TITLE
esd_core compile error 

### ISSUE THREAD

**Issue by brtchip-tuannguyen** [BRTSG-FOSS/EveApps#4]
There is compile error on esd_core  directory

![image](https://user-images.githubusercontent.com/48436368/131459252-1df4525a-a69e-4a92-9382-7646d831f4ca.png)

**Comment by brtchip-tuannguyen** [comment]
Will remove esd_core folder from the source code, it is not using by EveApps

**Comment by ftdi-paul-jiao** [comment]
pls check if building esd_core is removed from other platforms such as ft9xx, msvc building.

**Comment by brtchip-tuannguyen** [comment]
Checked on FT9xx toolchain and FT4222/MPSSE/Emulator, the build is done without issue. 

Command used on MSVC:
- cmake -G "NMake Makefiles" -DEVE_APPS_PLATFORM=BT8XXEMU -DEVE_APPS_GRAPHICS=EVE_GRAPHICS_BT817 -DEVE_DISPLAY=EVE_DISPLAY_WVGA ..
- cmake -G "NMake Makefiles" -DEVE_APPS_PLATFORM=FT4222 -DEVE_APPS_GRAPHICS=EVE_GRAPHICS_BT817 -DEVE_DISPLAY=EVE_DISPLAY_WVGA ..
- cmake -G "NMake Makefiles" -DEVE_APPS_PLATFORM=MPSSE -DEVE_APPS_GRAPHICS=EVE_GRAPHICS_BT817 -DEVE_DISPLAY=EVE_DISPLAY_WVGA ..
